import { Colors } from '@/constants/theme';
import { StyleSheet } from 'react-native';

const colors = Colors['light'];

/**
 * Estilos compartidos por las vistas/sub-componentes de resultados de encuestas.
 */
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.componentBackground,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    gap: 12,
  },
  resultadosButton: {
    minWidth: 80,
    height: 40,
    justifyContent: 'center',
  },
  resultadosButtonText: {
    fontSize: 14,
    color: colors.lightTint,
    fontWeight: '600',
  },
  subHeader: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
  },
  detailHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.background,
  },
  detailTitleContainer: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  detailHeaderTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'center',
  },
  descriptionContainer: {
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  detailDescription: {
    fontSize: 14,
    color: colors.secondaryText,
    textAlign: 'center',
  },
  deleteButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  retryButton: {
    marginTop: 16,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: colors.lightTint,
    borderRadius: 8,
  },
  retryButtonText: {
    color: colors.componentBackground,
    fontSize: 14,
    fontWeight: '600',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  anonimaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.background,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  anonimaText: {
    fontSize: 11,
    color: colors.secondaryText,
  },
  anonimaBadgeSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.background,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  anonimaTextSmall: {
    fontSize: 10,
    color: colors.secondaryText,
  },
  headerSubtitle: {
    fontSize: 14,
    color: colors.secondaryText,
  },
  listContent: {
    padding: 15,
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    padding: 15,
    paddingBottom: 50,
  },
  encuestaCard: {
    backgroundColor: colors.componentBackground,
    borderRadius: 12,
    padding: 16,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  encuestaTitulo: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    flex: 1,
  },
  creadorText: {
    fontSize: 13,
    color: colors.secondaryText,
    marginBottom: 8,
  },
  encuestaDescripcion: {
    fontSize: 14,
    color: colors.secondaryText,
    marginBottom: 15,
  },
  statsContainer: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: colors.background,
  },
  statItem: {
    flex: 1,
  },
  statLabel: {
    fontSize: 12,
    color: colors.secondaryText,
    marginBottom: 3,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.lightTint,
  },
  verDetalleButton: {
    flexDirection: 'row',
    backgroundColor: colors.lightTint,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  verDetalleText: {
    color: colors.componentBackground,
    fontSize: 14,
    fontWeight: '600',
  },
  preguntaResultadoCard: {
    backgroundColor: colors.componentBackground,
    borderRadius: 12,
    padding: 16,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  preguntaHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  preguntaNumero: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.lightTint,
  },
  tipoPreguntaBadge: {
    fontSize: 12,
    color: colors.secondaryText,
    backgroundColor: colors.componentBackground,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  preguntaTitulo: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 15,
  },
  respuestasContainer: {
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: colors.background,
  },
  respuestasHeader: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.secondaryText,
    marginBottom: 15,
  },
  promedioContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.componentBackground,
    padding: 15,
    borderRadius: 8,
    marginBottom: 15,
  },
  promedioLabel: {
    fontSize: 16,
    color: colors.secondaryText,
    marginRight: 10,
  },
  promedioValor: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.warning,
  },
  distribucionContainer: {
    gap: 8,
  },
  distribucionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  distribucionValor: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.secondaryText,
    width: 30,
  },
  barraContainer: {
    flex: 1,
    height: 24,
    backgroundColor: colors.componentBackground,
    borderRadius: 4,
    overflow: 'hidden',
  },
  barra: {
    height: '100%',
    backgroundColor: colors.warning,
  },
  distribucionCantidad: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    width: 30,
    textAlign: 'right',
  },
  respuestaTextoCard: {
    backgroundColor: colors.componentBackground,
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  respuestaTextoContenido: {
    fontSize: 14,
    color: colors.text,
    marginBottom: 10,
    lineHeight: 20,
  },
  respuestaFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.background,
  },
  respuestaAutor: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.lightTint,
  },
  respuestaFecha: {
    fontSize: 12,
    color: colors.secondaryText,
  },
  opcionResultadoCard: {
    marginBottom: 12,
  },
  opcionStatsWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  opcionTexto: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 8,
  },
  opcionStats: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flex: 1,
  },
  opcionBarra: {
    height: 24,
    backgroundColor: colors.lightTint,
    borderRadius: 4,
    maxWidth: '80%',
  },
  opcionPorcentaje: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.secondaryText,
    minWidth: 60,
  },
  siNoResultadosContainer: {
    flexDirection: 'row',
    gap: 15,
  },
  siNoItem: {
    flex: 1,
    backgroundColor: colors.componentBackground,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  siNoLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.secondaryText,
    marginBottom: 8,
  },
  siNoValor: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.lightTint,
  },
  siNoModalButton: {
    marginTop: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: colors.lightTint,
    borderRadius: 6,
    alignItems: 'center',
  },
  siNoModalButtonText: {
    color: colors.componentBackground,
    fontSize: 12,
    fontWeight: '600',
  },
  verRespondentesButtonInline: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: colors.lightTint,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verRespondentesText: {
    color: colors.componentBackground,
    fontSize: 12,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.componentBackground,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '80%',
    paddingBottom: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.background,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  modalCloseButton: {
    fontSize: 24,
    color: colors.secondaryText,
  },
  modalScroll: {
    paddingHorizontal: 20,
    marginTop: 10,
  },
  respondentCard: {
    backgroundColor: colors.background,
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  respondentContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  respondentInfo: {
    flex: 1,
  },
  respondentName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 4,
  },
  respondentDate: {
    fontSize: 12,
    color: colors.secondaryText,
  },
  respondentEmpty: {
    fontSize: 14,
    color: colors.secondaryText,
    textAlign: 'center',
    paddingVertical: 20,
  },
  enProgresoCartel: {
    flexDirection: 'row',
    backgroundColor: colors.warning,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  enProgresoText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.componentBackground,
  },
  errorSubtext: {
    fontSize: 14,
    color: colors.secondaryText,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: colors.secondaryText,
    textAlign: 'center',
  },
  emptySubtext: {
    fontSize: 14,
    color: colors.secondaryText,
    textAlign: 'center',
    marginTop: 5,
  },

  // ── Votantes inline ──────────────────────────────────────────────────────────
  votantesInlineContainer: {
    marginBottom: 8,
    gap: 6,
  },
  votanteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 7,
    paddingHorizontal: 10,
    backgroundColor: colors.background,
    borderRadius: 8,
  },
  votanteRowSelected: {
    backgroundColor: '#e9f1fd',
  },
  votanteRowConvocado: {
    backgroundColor: colors.background,
    opacity: 0.7,
  },
  yaConvocadoText: {
    fontSize: 11,
    color: colors.success,
    fontWeight: '600',
    marginTop: 1,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.secondaryText,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxSelected: {
    backgroundColor: colors.lightTint,
    borderColor: colors.lightTint,
  },
  votanteInfo: {
    flex: 1,
  },
  votanteNombre: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  votanteFecha: {
    fontSize: 12,
    color: colors.secondaryText,
    marginTop: 1,
  },
  slotBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#e9f1fd',
    borderWidth: 1,
    borderColor: '#cfe0f9',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  slotBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2a4f86',
  },
  verTodosButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 7,
    paddingHorizontal: 10,
    backgroundColor: colors.background,
    borderRadius: 8,
    marginBottom: 4,
  },
  verTodosText: {
    fontSize: 13,
    color: colors.lightTint,
    fontWeight: '600',
  },

  // ── Barra flotante de reunión ─────────────────────────────────────────────
  reunionBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.lightTint,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 20,
  },
  reunionBarText: {
    color: colors.componentBackground,
    fontSize: 15,
    fontWeight: '700',
  },
  reunionBarBadge: {
    backgroundColor: 'rgba(255,255,255,0.25)',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  reunionBarBadgeText: {
    color: colors.componentBackground,
    fontSize: 13,
    fontWeight: '700',
  },

  // ── ConvocarReunionModal ──────────────────────────────────────────────────
  convocarOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  convocarSheet: {
    backgroundColor: colors.componentBackground,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '90%',
    paddingBottom: 24,
  },
  convocarHandle: {
    width: 42,
    height: 5,
    backgroundColor: '#d3d7dd',
    borderRadius: 999,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 4,
  },
  convocarHeader: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.background,
  },
  convocarTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.text,
  },
  convocarSubtitle: {
    fontSize: 13,
    color: colors.secondaryText,
    marginTop: 2,
  },
  convocarBody: {
    paddingHorizontal: 20,
  },
  convocarFieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    marginTop: 16,
    marginBottom: 6,
  },
  convocarInput: {
    borderWidth: 1,
    borderColor: colors.background,
    borderRadius: 12,
    padding: 14,
    fontSize: 15,
    color: colors.text,
    backgroundColor: colors.componentBackground,
  },
  convocarTextArea: {
    minHeight: 72,
    textAlignVertical: 'top',
  },
  sepNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#e9f1fd',
    borderWidth: 1,
    borderColor: '#cfe0f9',
    borderRadius: 10,
    padding: 12,
    marginTop: 16,
  },
  sepNoteText: {
    fontSize: 12,
    color: '#2a4f86',
    flex: 1,
    lineHeight: 17,
  },
  convocarGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 16,
    marginBottom: 8,
  },
  convocarGroupSlot: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.lightTint,
    flex: 1,
  },
  convocarGroupCount: {
    fontSize: 12,
    color: colors.secondaryText,
  },
  personaReunionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.background,
  },
  personaReunionNombre: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    flex: 1,
  },
  fechaFinButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.background,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  fechaFinText: {
    fontSize: 12,
    color: colors.lightTint,
    fontWeight: '600',
  },
  convocarFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.background,
    marginTop: 8,
  },
  convocarFooterCount: {
    fontSize: 14,
    color: colors.secondaryText,
    fontWeight: '600',
  },
  enviarReunionButton: {
    backgroundColor: colors.lightTint,
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  enviarReunionButtonDisabled: {
    opacity: 0.5,
  },
  enviarReunionButtonText: {
    color: colors.componentBackground,
    fontSize: 15,
    fontWeight: '700',
  },
  fallidasContainer: {
    marginTop: 12,
    gap: 6,
  },
  fallidaRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#fff3f3',
    borderRadius: 8,
    padding: 10,
  },
  fallidaNombre: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.error,
  },
  fallidaError: {
    fontSize: 12,
    color: colors.secondaryText,
    marginTop: 2,
  },
  resultadosTitulo: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 8,
  },
  exitosasText: {
    fontSize: 14,
    color: colors.success,
    fontWeight: '600',
    marginBottom: 4,
  },

  // ── GestionParticipantesModal ─────────────────────────────────────────────
  tabBar: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.background,
    marginHorizontal: 20,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
  },
  tabButtonActive: {
    borderBottomWidth: 2,
    borderBottomColor: colors.lightTint,
  },
  tabButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.secondaryText,
  },
  tabButtonTextActive: {
    color: colors.lightTint,
  },
  participanteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.background,
  },
  participanteNombre: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    flex: 1,
  },
  participanteRol: {
    fontSize: 12,
    color: colors.secondaryText,
    marginTop: 1,
  },
  emptyParticipantes: {
    padding: 32,
    alignItems: 'center',
    gap: 8,
  },
  invitadosSection: {
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.background,
  },
  invitadosSectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 10,
  },
  invitadoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 7,
  },
  invitadoNombre: {
    fontSize: 14,
    color: colors.text,
    flex: 1,
  },
  gestionFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: colors.background,
  },
  gestionFooterLabel: {
    fontSize: 13,
    color: colors.secondaryText,
    fontWeight: '600',
  },
  gestionActionButton: {
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 100,
  },
  gestionAddButton: {
    backgroundColor: colors.lightTint,
  },
  gestionRemoveButton: {
    backgroundColor: colors.error,
  },
  gestionButtonDisabled: {
    opacity: 0.45,
  },
  gestionButtonText: {
    color: colors.componentBackground,
    fontSize: 14,
    fontWeight: '700',
  },
});