import { Colors } from '@/constants/theme';
import { StyleSheet } from 'react-native';

const colors = Colors['light'];

/**
 * Estilos compartidos por las vistas/sub-componentes de resultados de encuestas.
 */
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.componentBackground,
    paddingBottom: '20%' as any,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    gap: 12,
  },
  resultadosButton: {
    minWidth: 80,
    height: 40,
    justifyContent: 'center',
  },
  resultadosButtonText: {
    fontSize: 14,
    color: colors.lightTint,
    fontWeight: '600',
  },
  subHeader: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
  },
  detailHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.background,
  },
  detailTitleContainer: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  detailHeaderTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'center',
  },
  descriptionContainer: {
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  detailDescription: {
    fontSize: 14,
    color: colors.secondaryText,
    textAlign: 'center',
  },
  deleteButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  retryButton: {
    marginTop: 16,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: colors.lightTint,
    borderRadius: 8,
  },
  retryButtonText: {
    color: colors.componentBackground,
    fontSize: 14,
    fontWeight: '600',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  anonimaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.background,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  anonimaText: {
    fontSize: 11,
    color: colors.secondaryText,
  },
  anonimaBadgeSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.background,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  anonimaTextSmall: {
    fontSize: 10,
    color: colors.secondaryText,
  },
  headerSubtitle: {
    fontSize: 14,
    color: colors.secondaryText,
  },
  listContent: {
    padding: 15,
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    padding: 15,
    paddingBottom: 50,
  },
  encuestaCard: {
    backgroundColor: colors.componentBackground,
    borderRadius: 12,
    padding: 16,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  encuestaTitulo: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    flex: 1,
  },
  creadorText: {
    fontSize: 13,
    color: colors.secondaryText,
    marginBottom: 8,
  },
  encuestaDescripcion: {
    fontSize: 14,
    color: colors.secondaryText,
    marginBottom: 15,
  },
  statsContainer: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: colors.background,
  },
  statItem: {
    flex: 1,
  },
  statLabel: {
    fontSize: 12,
    color: colors.secondaryText,
    marginBottom: 3,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.lightTint,
  },
  verDetalleButton: {
    flexDirection: 'row',
    backgroundColor: colors.lightTint,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  verDetalleText: {
    color: colors.componentBackground,
    fontSize: 14,
    fontWeight: '600',
  },
  preguntaResultadoCard: {
    backgroundColor: colors.componentBackground,
    borderRadius: 12,
    padding: 16,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  preguntaHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  preguntaNumero: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.lightTint,
  },
  tipoPreguntaBadge: {
    fontSize: 12,
    color: colors.secondaryText,
    backgroundColor: colors.componentBackground,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  preguntaTitulo: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 15,
  },
  respuestasContainer: {
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: colors.background,
  },
  respuestasHeader: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.secondaryText,
    marginBottom: 15,
  },
  promedioContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.componentBackground,
    padding: 15,
    borderRadius: 8,
    marginBottom: 15,
  },
  promedioLabel: {
    fontSize: 16,
    color: colors.secondaryText,
    marginRight: 10,
  },
  promedioValor: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.warning,
  },
  distribucionContainer: {
    gap: 8,
  },
  distribucionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  distribucionValor: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.secondaryText,
    width: 30,
  },
  barraContainer: {
    flex: 1,
    height: 24,
    backgroundColor: colors.componentBackground,
    borderRadius: 4,
    overflow: 'hidden',
  },
  barra: {
    height: '100%',
    backgroundColor: colors.warning,
  },
  distribucionCantidad: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    width: 30,
    textAlign: 'right',
  },
  respuestaTextoCard: {
    backgroundColor: colors.componentBackground,
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  respuestaTextoContenido: {
    fontSize: 14,
    color: colors.text,
    marginBottom: 10,
    lineHeight: 20,
  },
  respuestaFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.background,
  },
  respuestaAutor: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.lightTint,
  },
  respuestaFecha: {
    fontSize: 12,
    color: colors.secondaryText,
  },
  opcionResultadoCard: {
    marginBottom: 12,
  },
  opcionStatsWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  opcionTexto: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 8,
  },
  opcionStats: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    flex: 1,
  },
  opcionBarra: {
    height: 24,
    backgroundColor: colors.lightTint,
    borderRadius: 4,
    maxWidth: '80%',
  },
  opcionPorcentaje: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.secondaryText,
    minWidth: 60,
  },
  siNoResultadosContainer: {
    flexDirection: 'row',
    gap: 15,
  },
  siNoItem: {
    flex: 1,
    backgroundColor: colors.componentBackground,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  siNoLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.secondaryText,
    marginBottom: 8,
  },
  siNoValor: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.lightTint,
  },
  siNoModalButton: {
    marginTop: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: colors.lightTint,
    borderRadius: 6,
    alignItems: 'center',
  },
  siNoModalButtonText: {
    color: colors.componentBackground,
    fontSize: 12,
    fontWeight: '600',
  },
  verRespondentesButtonInline: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: colors.lightTint,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verRespondentesText: {
    color: colors.componentBackground,
    fontSize: 12,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.componentBackground,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '80%',
    paddingBottom: '20%' as any,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.background,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  modalCloseButton: {
    fontSize: 24,
    color: colors.secondaryText,
  },
  modalScroll: {
    paddingHorizontal: 20,
    marginTop: 10,
  },
  respondentCard: {
    backgroundColor: colors.background,
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  respondentContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  respondentInfo: {
    flex: 1,
  },
  respondentName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 4,
  },
  respondentDate: {
    fontSize: 12,
    color: colors.secondaryText,
  },
  respondentEmpty: {
    fontSize: 14,
    color: colors.secondaryText,
    textAlign: 'center',
    paddingVertical: 20,
  },
  enProgresoCartel: {
    flexDirection: 'row',
    backgroundColor: colors.warning,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  enProgresoText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.componentBackground,
  },
  errorSubtext: {
    fontSize: 14,
    color: colors.secondaryText,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: colors.secondaryText,
    textAlign: 'center',
  },
  emptySubtext: {
    fontSize: 14,
    color: colors.secondaryText,
    textAlign: 'center',
    marginTop: 5,
  },
});